query GetProject($id: ID!) {
  project(id: $id) {
    id
    name
    description
    state
    platform
    region
    uri
    creationDate
    modifiedDate
    owner {
      id
    }
    quota {
      storage
      contents
      credits
      feeds
      posts
      conversations
      userCredits
    }
    environments {
      id
      name
      type
      state
      jwtSecret
      uri
      serviceClients {
        name
        clientId
        scopes
        role
        state
        createdAt
        keys {
          name
          kid
          kty
          alg
          use
          publicJwk
          publicKeyFingerprint
          state
          createdAt
        }
      }
    }
    subscription {
      status
      identifier
      description
      products {
        name
        identifier
      }
    }
  }
}
