query GetProject($id: ID!) {
  project(id: $id) {
    id
    name
    description
    state
    platform
    region
    uri
    creationDate
    modifiedDate
    owner {
      id
    }
    quota {
      storage
      contents
      credits
      feeds
      posts
      conversations
      userCredits
    }
    environments {
      id
      name
      type
      state
      jwtSecret
      uri
    }
    subscription {
      status
      identifier
      description
      products {
        name
        identifier
      }
    }
  }
}
