query QueryProjects($filter: ProjectFilter) {
  projects(filter: $filter) {
    results {
      id
      name
      description
      state
      platform
      region
      uri
      creationDate
      modifiedDate
      owner {
        id
      }
      quota {
        credits
        contents
        feeds
        conversations
        storage
      }
      environments {
        id
        name
        type
        state
        jwtSecret
        uri
      }
      subscription {
        status
        identifier
        description
        products {
          name
          identifier
        }
      }
    }
  }
}
